### ISSUE TITLE
Add related object popup error prevents operation when no related objects already exist

### ISSUE THREAD

**Issue by mkoistinen** [gregmuellegger/django-sortedm2m#57]
Using sortedm2m's :heavy_plus_sign: in a change form to add a related object works fine when related objects exist, but fails when there are none to start with.

I have demonstrated this with [this concise video](https://youtu.be/TNlezwxCtsk). This was made using a pristine virtenv and installing only Django v1.7.9 and django-sortedm2m v1.0.1. Here is a link to my [project files](http://cl.ly/0f1O180g1a0f) for your testing pleasure. admin account = admin/password.

**Comment by gregmuellegger** [comment]
Whoops, ok. Not a good thing to have. However I'm not using the widget myself so far so I don't have any resources to fix this soonish.

Would you like to help out with this issue?

**Comment by mkoistinen** [comment]
I would be happy to. In fact, I already tried to make a PR, but I got lost in the JS... both that of this project and Django's. I'm afraid I don't understand enough about this widget to know exactly what the issue is, nor how to fix it. I wonder if @johnraz has adequate experience here? =)

**Comment by johnraz** [comment]
Long time not talked @mkoistinen ! 

Hard to tell what the issue is from the top of my head, but from what I'm reading so far it seems that `dismissAddAnotherPopup` is not overridden correctly [here](https://github.com/gregmuellegger/django-sortedm2m/blob/master/sortedm2m/static/sortedm2m/widget.js#L61) and [this](https://github.com/django/django/blob/1.7.9/django/contrib/admin/static/admin/js/admin/RelatedObjectLookups.js#L69) django javascript code is executed instead...

@mkoistinen : did your former attempt show anything related to that ?

**Comment by gregmuellegger** [comment]
@mkoistinen I would be happy with a complete reimplementation if that would clean-up things. Or make the code better. Feel free to do what is needed to make it work and/or better :)

**Comment by mkoistinen** [comment]
WTG @vxsx!

**Comment by gregmuellegger** [comment]
Fixed :) https://pypi.python.org/pypi/django-sortedm2m
