### ISSUE TITLE
Using a "through" intermediate model

### ISSUE THREAD

**Issue by bjesus** [gregmuellegger/django-sortedm2m#77]
Hi,
I couldn't get sortedm2m to work when tried with an intermediate model. Without it works perfectly.

My code is like this:
```
class Photo(models.Model):
    file = models.ImageField()

class Gallery(models.Model):
    name = models.CharField(max_length=1000, default="")
    photos = SortedManyToManyField(Photo, through="PhotosToGalleries")

class PhotosToGalleries(models.Model):
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    featured = models.BooleanField()
```

All seems fine, but I see nothing in the admin panel, and when trying to run `some_gallery_object.photos.all()` I the following error:
`AttributeError: type object 'PhotosToGalleries' has no attribute '_sort_field_name'`

Does sortedm2m supports defining my own intermediate model?

I'm using Django 1.9.5 with Python 3.

Thanks

**Comment by gregmuellegger** [comment]
Hi. No sortedm2m does not support using through models officially (i.e. I have never tried it with an intermediate model). Sortedm2m works the very same way as a Django ManyToManyField, but it creates its own through model on the fly so we can have a "sort_value" field.

I assume you can use your own through model, but it must support all the implicit interface that the auto-created through model has as well, so that it plays nicely with the rest of the sortedm2m library.

Have a look in the code here to get an idea on what the through model needs to have as attributes: https://github.com/gregmuellegger/django-sortedm2m/blob/master/sortedm2m/fields.py#L390
You must also not forget to set the `ordering` in your model's `Meta`, otherwise you won't get any sorting at all ;)

I'm happy to accept any pull requests that improve the handling of custom through models. We might start with a check that is run on the custom passed through argument, to see if everything required is implemented. Another solution could be that sortedm2m provides an abstract base class that could be used for through models so that you don't need to repeat all the work on every custom through model.

What do you think?

**Comment by shanrod220** [comment]
Hi,
Ive come across a similar issue in one of my apps. Since I'm a beginner, I'm kinda lost with your instructions. Could you give me a few more details on how to make my own through model and implement it in SortedManyToManyField (if its not the same as ManyToManyField)?
An abstract base class would be a great idea

Thanks

**Comment by gregmuellegger** [comment]
Closing this as I assume the questions raised in the issue are answered. Feel free to open a new one or comment here if there are still questions open.

**Comment by maazsabahuddin** [comment]
I have implemented sortedm2m SortedManyToManyField in my project. It works fine. But now I want the sort_value? How will I get it?
